POST localhost:3000/books
Content-Type: application/json

[
  {
    "title": "Golang New 1",
    "author": "Tom Smith",
    "year": 2014
  },
  {
    "title": "Golang New 2",
    "author": "Tom Smith",
    "year": 2016
  }
]

### Get all books
GET localhost:3000/books
Content-Type: application/json

### Update books
PUT localhost:3000/books
Content-Type: application/json

[
  {
    "id": "5493dbd9-41e5-4ada-a232-5d5a476dad3f",
    "title": "Golang New Name",
    "author": "Ron Wesley",
    "year": 2019
  },
  {
    "id": "1292a575-261d-429b-bebd-d58ef586c600",
    "title": "Golang 2 New",
    "author": "John M Doe",
    "year": 2005
  }
]

### Delete a book
DELETE localhost:3000/books/9b21d170-854b-4985-af9b-363f7151b767
Content-Type: application/json


### Get a single book
GET localhost:3000/books/d8ea5bdb-eb10-42ad-b52a-bb3f6fda4d54
Content-Type: application/json
